[satellites.ETROC2Classic]

[satellites.ETROC2Classic.One]
fast_command_memo = "Start Triggerbit"
polarity = 0x4023
active_channel = 0x1
timestamp = 0x0
triggerbit_delay = 0x1de6
# fc_delays = 0b0000000000000101

[satellites.ETROC2Receiver]

[satellites.ETROC2Receiver.One]
output_path = "/home/daq/ETROC2/ETROC-Data/cosmic_binary"
translate = 0
compressed_binary = 1
skip_fillers = 1
